/**
 * The 'Student' page allows students to view their upcoming quizzes.
 * Clicking on a quiz will take them to perform that quiz
 * 
 * Sections -> upcoming, available
 *          -> upcoming, cannot take yet
 **/
import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

interface Quiz {
    id: number,
    name: string,
    start_date: Date,
    end_date: Date,

}

const SampleQuizzes: Quiz[] = [
    {
        id: 0,
        name: 'Beginner spatial reasoning',
        start_date: new Date(),
        end_date: new Date()
    }
]

const Student: NextPage = () => {
    return (
        <div className={styles.container}>

            <Head>
                <title>student homepage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className="">
                    student home
                </h1>
                <div>
                    {
                        SampleQuizzes.map((quiz) => {
                            return (
                                <div key={`quiz-${quiz.id}`}>
                                    <h1>{quiz.name}</h1>
                                    <p>{quiz.start_date.toDateString()}</p>
                                </div>
                            )
                        })
                    }
                </div>
            </main>
        </div>
    )
};

export default Student;