/**
 * The 'index' page is the main page for this site.  If the user is signed out, we
 * will show a landing page.  If a student is logged in, they should see '_student.tsx'
 * If an instructor is logged in, they should see '_instructor.tsx'.
 **/
import type { NextPage } from 'next';
import { Dispatch, SetStateAction, useState } from 'react';
import Head from 'next/head';
import Instructor from './_instructor';
import Student from './_student';

type Page = 'Home' | 'Instructor' | 'Student';

interface HomeProps {
  setPage: Dispatch<SetStateAction<Page>>
}

const Home: NextPage<HomeProps> = ({ setPage }) => {
  // TODO: this should be our landing page.  here, display some cool info
  // about our website, and some login buttons.  these will not be included in the
  // header
  return (
    <>

      <Head>
        <title>spatial skills test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">

        <p className="dark:text-white">
          a website for testing your spatial skills
        </p>

        <div className="">
          <a onClick={() => setPage('Instructor')} className="">
            <h2>instructors &rarr;</h2>
            <p>log in here</p>
          </a>

          <a onClick={() => setPage('Student')} className="">
            <h2>students &rarr;</h2>
            <p>enter your access code</p>
          </a>
        </div>
      </main>

      <footer className="">
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          CS399 Team 34 | Project 14
        </a>
      </footer>
    </>
  )
}

const PageSelect: NextPage = () => {
  // NOTE: this is temporary.  once auth is implemented,
  // which page is shown here depends on what type of user
  // is logged in

  // HOME -> logged out, show login buttons
  // INSTRUCTOR -> instructor is logged in
  // STUDENT -> student is loggen in
  const [page, setPage] = useState<Page>('Home');

  return (
    <div className="">
      {page === 'Home' && <Home setPage={setPage} />}
      {page === 'Instructor' && <Instructor />}
      {page === 'Student' && <Student />}
    </div>
  )
};

export default PageSelect
