/**
 * The 'index' page is the main page for this site.  If the user is signed out, we
 * will show a landing page.  If a student is logged in, they should see '_student.tsx'
 * If an instructor is logged in, they should see '_instructor.tsx'.
 **/
import type { GetServerSideProps, NextPage } from 'next';
import { unstable_getServerSession } from 'next-auth';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { authOptions } from './api/auth/[...nextauth]';
import { isStudent } from '@/lib/util';

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await unstable_getServerSession(context.req, context.res, authOptions);

    if (session?.user && !isStudent(session)) {
        return { props: {} };
    } else {
        return { props: {} };
    }
};

interface IndexProps {
}

const Index: NextPage<IndexProps> = ({ }) => {
    const { data: session, status } = useSession()
    const loading = status === "loading";
    const router = useRouter();

    if (!session || isStudent(session)) {
        router.replace('/');
    }

    return (
        <>
            <Head>
                <title>spatial skills test</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                loading ? (
                    <p>loading... {/* TODO: draw some spinner element or something */}</p>
                ) : (
                    <p className="text-white text-3xl p-4">Instructor settings page</p>
                )
            }
        </>
    )
};

export default Index
